sysParams = ['synaptic_elements',
             'consistent_integration',
             'element_type',
             'local',
             # 'recordables',
             'thread_local_id',
             'thread',
             'frozen',
             'archiver_length',
             'global_id',
             'local_id',
             'available',
             'capacity',
             'instantiations',
             'needs_prelim_update',
             'model',
             'has_connections',
             'type_id',
             'vp',
             'elementsize']

rec_params = ['V_m',
              'g_ex',
              'g_in',
              'w',
              'V_th',
              'V_th_v',
              'Act_h',
              'Act_m',
              'Inact_n',
              'I_ex',
              'I_in',
              'Inact_p',
              'g_ahp',
              'I_syn_exc',
              'I_syn_inh',
              'I_ahp',
              't_ref_remaining',
              'g_rr',
              'g_sfa',
              'input_currents_ex',
              'input_currents_in',
              'weighted_spikes_ex',
              'weighted_spikes_in',
              'I_syn_ex',
              'I_syn_in',
              'U_m',
              'n_events',
              'E_sfa']

neuron_param = {'V_m': -44.,
                'E_L': -65.,
                'C_m': 33.,
                'V_reset': -70.,
                #'tau_syn_ex': 1.0,
                #'V_min': -80.
                }
